[project]
name = "test-new"
version = "0.1.0"
description = ""

authors = [
  { name = "Tommy Larsson"}
]
license = "MPL-2.0"
license-files = [
    "LICENSE.md",
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "build123d>=0.9.1,<1",
    "rich>=14.0.0,<15",
    "mashumaro>=3.16,<4",
    "more-itertools>=10.7.0,<11",
    "attrs>=25.3.0,<26",
    "tzdata>=2025.2",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries",
  "Topic :: Multimedia :: Graphics :: 3D Modeling",
]
keywords = []
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
  "D",
  "B",      # flake8-bugbear
  "TC",     # flake8-type-checking
  "C4",     # Helps you write better list/set/dict comprehensions.
  "E",      # pycodestyle errors
  "FA",     # Verifies files use from __future__ import annotations if a type is used in the module that can be rewritten using PEP 563.
  "F",      # pyflakes
  "G",      # Better usage of built-in logging
  "I",      # isort - Import sorting
  "LOG",    # Checks for issues using the standard library logging module.
  "PL",     # pylint
  "PYI",    # Linting rules for type annotations.
  "Q",      # Linting rules for quites
  "RUF",    # Ruff lint
  "TID",    # Helps you write tidier imports.
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
  "SIM",    # flake8-simplify
  "TRY",    # Tryceratops - For those who like dinosaurs 🦖 and clean try/except ✨ blocks.
]

ignore = [
  "TRY003" # Checks for long exception messages that are not defined in the exception class itself.
]

[tool.ruff.lint.per-file-ignores]
"src/tests/**/*.py" = ["PLR2004", "D", "PLR0913"]
"examples/**/*.py" = ["PLR2004", "D", "F403", "F405"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.codespell]
skip = "*.lock, *.step"
count = true
quiet-level = 3
ignore-words-list = "strat"

[dependency-groups]
dev = [
  "pre-commit",
  "pytest",
  "pytest-xdist",
  "pytest-sugar",
  "pytest-cov",
  "removestar",
  "hypothesis[cli]",
  "icecream",
  "pylint",
  "pdoc",
  "ocp_vscode",
  "codespell",
  "pre-commit"
]

[tool.basedpyright]
typeCheckingMode = "basic"
reportUnusedImport = "none"
reportUndefinedVariable = "warning"
reportUnusedCallResult = "none"

[tool.pytest.ini_options]
addopts = """
  --cov=src
  --cov-report=term-missing
  --cov-report=html
  """
